logging:
  level:
    com:
      springtest:
        learningwebflux: DEBUG
    org:
      springframework:
        data: TRACE
    reactor:
      core: DEBUG
      util: TRACE


management:
  endpoints:
    web:
      base-path: /application
      exposure:
        include: "*"
  endpoint:
    configprops:
      enabled: true
    health:
      enabled: true
      show-details: always
#spring:
#  profiles:
#    active: simulator

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-comments
          group: learning-spring-boot
        output:
          destination: learning-spring-boot-comments
          group: learning-spring-boot